[OCPCLOUD-1506] Disable defaulting webhook for cluster objects
openshift/cluster-capi-operator pull request #51
Opened 2022-05-03 14:50 UTC by Fedosin

We don't need CAPI to set any default to the cluster object because we have a custom controller for reconciling it.

This PR drops all MutatingWebhookConfigurations via the import assets logic to prevent the defaulting.

2022-05-04 10:50 UTC, alexander-demichev commented on hack/assets/providers.go
> +		for _, obj := range p.components.Objs() {
These better be handled here https://github.com/openshift/cluster-capi-operator/blob/main/hack/assets/customizations.go#L51. The code also removes webhooks for machine, machinesets, etc., but it should only remove webhook from the generic clusters and all infra clusters.

2022-05-06 15:14 UTC, alexander-demichev requested changes

2022-05-06 15:14 UTC, alexander-demichev commented on hack/assets/providercustomizations.go
> +		case "default.cluster.cluster.x-k8s.io",
can we make this list more dynamic as more providers will be added in the future?

2022-05-11 19:43 UTC, Fedosin commented
/retest

2022-05-12 10:35 UTC, alexander-demichev commented
/retest

2022-05-12 16:18 UTC, Fedosin commented
/test images

2022-05-13 10:20 UTC, Fedosin commented
/retest

2022-05-13 12:47 UTC, lobziik commented
/lgtm

2022-05-13 12:48 UTC, lobziik commented
/approve

2022-05-13 12:49 UTC, elmiko reviewed
this generally looks good to me, i'm not 100% sure on that regex for the webhook kind, but it looks correct to me.
/lgtm

2022-05-13 15:09 UTC, Fedosin commented
/test e2e-gcp-capi-techpreview

2022-05-15 03:18 UTC, merged